spring:
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
server:
  port: 8090
  compression:
    enabled: true
  servlet:
    context-path: /mi-profe
logging:
  level:
   org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  profiles: default
  data:
    mongodb:
      database: profelocal