spring:
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
server:
  port: 8090
  compression:
    enabled: true
logging:
  level:
    org.springframework.data.*: DEBUG

---
spring:
  data:
    mongodb:
      database: examsManagerLocal
  profiles:
    active: local
---
spring:
  profiles: dev
  data:
    mongodb:
      database: exams-manager-dev